// PSDL 0.2 — runtime constants.
//
// Category labels, byte-order copy, preset grouping, theme storage key. The
// category → CSS variable mapping lives in `./render-tokens.ts` (renderer
// intent, not schema metadata). This file re-exports the common items so
// existing component imports stay one-stop.

import type { CategoryToken } from "./psdl/renderer";

export {
  CATEGORY_TO_TOKEN,
  FIELD_PALETTE_TOKENS,
  tokenToCssVar,
  type ColorToken,
} from "./render-tokens";

// Human-readable labels for the semantic categories used in the legend.
export const CATEGORY_LABELS: Record<CategoryToken, string> = {
  addressing: "Addressing",
  identifier: "Identifier / sequencing",
  length: "Length / size",
  type: "Type / protocol selector",
  flags: "Flags / control bits",
  reserved: "Reserved / padding",
  checksum: "Checksum / integrity",
  variable: "Variable-length options",
  "payload-marker": "Payload marker",
};

export const DEFAULT_BYTE_ORDER = "Network byte order (big-endian, MSB-first).";

// Curriculum-ordered grouping of presets by OSI layer.
export const PRESET_GROUPS: ReadonlyArray<{ label: string; keys: string[] }> = [
  {
    label: "Layer 2 — Link",
    keys: [
      "ethernet",
      "vlan",
      "arp",
      "stpBpdu",
      "ieee80211Mac",
      "ppp",
      "mpls",
      "l2tp",
      "pppoe",
      "lldp",
      "eapol",
      "eap",
      "lacp",
      "macsec",
      "l2tpControl",
    ],
  },
  {
    label: "Layer 3 — Network",
    keys: [
      "ipv4",
      "ipv6",
      "icmp",
      "icmpv6",
      "ospfHello",
      "isisLsp",
      "igmpv3Query",
      "gre",
      "ipsecAh",
      "ipsecEsp",
      "ripv2",
      "pimHello",
      "ipv6Fragment",
      "ipv6HopByHop",
      "icmpv6Ndp",
      "vrrp",
      "igmpv2",
      "mldv2Query",
      "bfd",
      "ospfv3Hello",
      "ipv6Routing",
      "ipv6Destination",
      "rsvpPath",
      "ripng",
      "ripv1",
      "ospfLsUpdate",
      "ospfLsAck",
      "ospfLsRequest",
      "babel",
      "pimJoinPrune",
      "pimRegister",
      "igmpv3Report",
      "mldv2Report",
      "icmpRouterAdvert",
      "msdp",
      "eigrp",
      "mobilityHeader",
      "hip",
      "srhv6",
      "dvmrp",
      "pimAssert",
      "pimBootstrap",
      "send",
      "lispMapRequest",
      "lispMapReply",
      "bgpFlowSpec",
      "sctpAuth",
      "pimHelloOptions",
      "ospfv3LsUpdate",
      "rsvpTe",
      "bgpLs",
      "vrrpv2",
      "pgm",
    ],
  },
  {
    label: "Layer 4 — Transport",
    keys: ["tcp", "udp", "sctp", "quicShort", "quicLong", "dccp", "udpLite"],
  },
  {
    label: "Overlay / Tunneling",
    keys: [
      "vxlan",
      "geneve",
      "gtpv1u",
      "gtpv2c",
      "teredo",
      "lisp",
      "vxlanGpe",
      "ipinip",
      "nvgre",
      "l2tpv3",
      "espInUdp",
      "amt",
      "nsh",
      "mplsPwControlWord",
      "rohcUncompressed",
      "capwap",
      "gtpv1c",
      "dhcpv6Relay",
    ],
  },
  {
    label: "Layer 7 — Application",
    keys: [
      "dns",
      "dnsResponse",
      "dhcpv4",
      "bgpUpdate",
      "bgpUpdateFull",
      "ospfDbDescription",
      "coap",
      "mqttConnect",
      "websocketFrame",
      "tlsRecord",
      "tlsClientHello",
      "tlsClientHelloFull",
      "ntp",
      "dhcpv6",
      "rtp",
      "rtcpSr",
      "radius",
      "bgpOpen",
      "bgpNotification",
      "stun",
      "dtlsRecord",
      "sshBinary",
      "snmpV2c",
      "tftp",
      "syslog",
      "diameter",
      "ikev2",
      "bgpKeepalive",
      "bgpRouteRefresh",
      "http3Frame",
      "tlsServerHello",
      "tlsHandshake",
      "ipfix",
      "netflowV5",
      "quicVersionNegotiation",
      "isakmp",
      "ocspRequest",
      "socks5",
      "tacacsPlus",
      "snmpv3",
      "pcp",
      "natPmp",
      "slp",
      "rtcpRr",
      "rtcpSdes",
      "rtcpBye",
      "turnChannelData",
      "bmp",
      "pcep",
      "ldp",
      "dnssecRecords",
      "ednsOpt",
      "llmnr",
      "netbiosNs",
      "oncRpc",
      "portmap",
      "iscsiBhs",
      "tlsAlert",
      "tlsChangeCipherSpec",
      "dtlsHandshake",
      "radiusCoa",
      "cops",
      "twamp",
      "owamp",
      "kerberosAsReq",
      "gist",
      "ancp",
      "psamp",
      "bootp",
      "ikev2Sa",
      "ikev2Ke",
      "ikev2Notify",
      "coapSignaling",
      "oscore",
      "lwm2mRegister",
      "nfsv3Read",
      "smbHeader",
      "tlsNewSessionTicket",
      "tlsCertificate",
      "dtlsClientHello",
      "sflow",
      "rtmp",
      "syslogTls",
      "radiusAccounting",
      "ntpControl",
      "mdns",
      "dnsUpdate",
      "tsig",
    ],
  },
];

export const THEME_STORAGE_KEY = "packet-schema-visualizer-theme";

export const FIELD_FILL_OPACITY = 0.78;
