// Build-time conversion of data/presets.typ → lib/presets.generated.ts.
//
// Reads the Typst source, runs it through our minimal Typst parser, validates
// each preset against the Packet type, and emits a TypeScript module that
// exports a typed PRESETS registry plus PRESET_KEYS.
//
// Re-attaches `toBits` lazily at runtime via lib/packet-resolver.ts so the
// generated file stays pure JSON-like.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { parseTypst, type JsValue } from "../lib/typst-parser";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const srcPath = resolve(root, "data/presets.typ");
const outPath = resolve(root, "lib/presets.generated.ts");

function isPlainObject(v: JsValue): v is { [key: string]: JsValue } {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

function asObj(v: JsValue, ctx: string): { [key: string]: JsValue } {
  if (!isPlainObject(v)) {
    throw new Error(`build-presets: expected dict at ${ctx}, got ${typeof v}`);
  }
  return v;
}

function asArr(v: JsValue, ctx: string): JsValue[] {
  if (!Array.isArray(v)) {
    throw new Error(`build-presets: expected array at ${ctx}, got ${typeof v}`);
  }
  return v;
}

function validatePreset(key: string, v: JsValue): void {
  const p = asObj(v, `presets.${key}`);
  if (typeof p.name !== "string") {
    throw new Error(`build-presets: preset "${key}" missing string name`);
  }
  if (typeof p.rowBits !== "number") {
    throw new Error(`build-presets: preset "${key}" missing numeric rowBits`);
  }
  const fields = asArr(p.fields, `presets.${key}.fields`);
  for (let i = 0; i < fields.length; i++) {
    const f = asObj(fields[i], `presets.${key}.fields[${i}]`);
    if (typeof f.id !== "string" || typeof f.name !== "string") {
      throw new Error(
        `build-presets: preset "${key}" field[${i}] missing id/name`,
      );
    }
    if (f.variable === true) {
      if (typeof f.lengthFrom !== "string" || typeof f.formula !== "string") {
        throw new Error(
          `build-presets: preset "${key}" variable field "${String(f.id)}" must have lengthFrom and formula`,
        );
      }
    } else if (typeof f.bits !== "number") {
      throw new Error(
        `build-presets: preset "${key}" field "${String(f.id)}" missing bits`,
      );
    }
  }
}

function main(): void {
  const src = readFileSync(srcPath, "utf8");
  const env = parseTypst(src);
  const presets = env["presets"];
  if (!presets || !isPlainObject(presets)) {
    throw new Error(`build-presets: data/presets.typ must define a 'presets' dict`);
  }
  for (const key of Object.keys(presets)) {
    validatePreset(key, presets[key]);
  }

  const header = `// AUTO-GENERATED by scripts/build-presets.ts.
// Edit data/presets.typ and run \`npm run build:data\` instead.

import { attachToBits } from "./packet-resolver";
import type { Packet, PacketRegistry } from "./types";

const RAW_PRESETS = ${JSON.stringify(presets, null, 2)} as unknown as PacketRegistry;

// Attach toBits functions for variable-length fields. attachToBits mutates
// each Packet but we accept that — these objects are created once at module
// load and are not shared with persisted state.
for (const key of Object.keys(RAW_PRESETS)) {
  attachToBits(RAW_PRESETS[key]);
}

export const PRESETS: PacketRegistry = RAW_PRESETS;
export const PRESET_KEYS = Object.keys(PRESETS) as Array<keyof typeof PRESETS & string>;
export type { Packet };
`;

  writeFileSync(outPath, header, "utf8");
  console.log(`build-presets: wrote ${outPath} (${Object.keys(presets).length} preset(s))`);
}

main();
