// Build-time code generator for the PSDL editor schema.
//
// Built-in presets now live in `@packet-schema/presets` (no longer generated
// here). This script's remaining job is to emit `psdl.schema.generated.ts` —
// a TS module wrapping the canonical PSDL JSON Schema so the in-browser editor
// can Ajv-lint source without importing a file from outside the web bundle.
//
// The generated file is gitignored; it is recreated on every `npm run
// build:presets`, which is wired into `prebuild` / `pretest` so neither
// `next build` nor `vitest` runs against a stale schema.
//
// The schema source is now the canonical PSDL 0.5 JSON Schema shipped by
// `@packet-schema/core` (`schemas/psdl-0.5.yaml`). It is authored as YAML, so
// we parse it with the `yaml` package and emit it as JSON-shaped TS. This
// keeps the editor lint in lock-step with the schema the presets are authored
// under (PSDL 0.5), rather than the stale in-repo 0.4 JSON Schema.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { parse as parseYaml } from "yaml";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const REPO_ROOT = resolve(__dirname, "..", "..");
// Canonical PSDL 0.5 schema ships inside @packet-schema/core. Resolve it from
// the web/ node_modules so this works regardless of the repo's hoisting.
const WEB_ROOT = join(REPO_ROOT, "web");
const SCHEMA_PATH = join(
  WEB_ROOT,
  "node_modules",
  "@packet-schema",
  "core",
  "schemas",
  "psdl-0.5.yaml",
);
// editor 側で Ajv lint に使うための schema TS export。 schema 自体は
// node_modules にあって browser bundle から直接 import できないので、
// web/ 配下にコピー TS を吐く。
const SCHEMA_OUT_PATH = join(
  WEB_ROOT,
  "lib",
  "psdl",
  "psdl.schema.generated.ts",
);

function main(): void {
  const schema = parseYaml(readFileSync(SCHEMA_PATH, "utf8"));

  const schemaSrc =
    "// AUTO-GENERATED by scripts/build-presets.ts. DO NOT EDIT.\n" +
    "// Source: @packet-schema/core schemas/psdl-0.5.yaml — keep in lock-step.\n" +
    "// eslint-disable\n" +
    "/* prettier-ignore */\n" +
    "export const PSDL_JSON_SCHEMA = " +
    JSON.stringify(schema, null, 2) +
    " as const;\n";

  mkdirSync(dirname(SCHEMA_OUT_PATH), { recursive: true });
  writeFileSync(SCHEMA_OUT_PATH, schemaSrc, "utf8");
  console.log(`Wrote ${relative(REPO_ROOT, SCHEMA_OUT_PATH)}.`);
}

main();
