// Build-time code generator for the PSML preset registry.
//
// Reads every `data/presets/*.psml.yaml` from the repo root, validates each
// document against `schemas/psml.schema.json` (the canonical PSML 0.4 schema),
// and emits a single TS module — `web/lib/psml/presets.generated.ts` — that
// exports the `PRESETS` map consumed by the renderer.
//
// The generated file is gitignored; it is recreated on every `npm run
// build:presets`, which is wired into `prebuild` and `pretest` so neither
// `next build` nor `vitest` can run against a stale registry.
//
// Adding or editing a preset: drop a new `.psml.yaml` into `data/presets/`
// and re-run `npm run build:presets`. No TS edits required.

import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { basename, dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parse as parseYaml } from "yaml";
import Ajv2020 from "ajv/dist/2020.js";
import addFormats from "ajv-formats";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const REPO_ROOT = resolve(__dirname, "..", "..");
const PRESETS_DIR = join(REPO_ROOT, "data", "presets");
const SCHEMA_PATH = join(REPO_ROOT, "schemas", "psml.schema.json");
const OUT_PATH = join(REPO_ROOT, "web", "lib", "psml", "presets.generated.ts");

// PSML schema requires top-level `format` and `version` (the on-wire JSON
// shape). The in-memory PsmlPacket type does not carry them — they are
// injected here for validation only and stripped before emission.
const FORMAT_TAG = "psml";
const FORMAT_VERSION = "0.4";

type PresetDoc = Record<string, unknown>;

function loadSchema(): unknown {
  const text = readFileSync(SCHEMA_PATH, "utf8");
  return JSON.parse(text);
}

function listYamlFiles(): string[] {
  const entries = readdirSync(PRESETS_DIR);
  return entries
    .filter((f) => f.endsWith(".psml.yaml"))
    .sort()
    .map((f) => join(PRESETS_DIR, f));
}

function keyFromFilename(path: string): string {
  const base = basename(path);
  return base.replace(/\.psml\.yaml$/, "");
}

function stripValidationFields(doc: PresetDoc): PresetDoc {
  const out: PresetDoc = {};
  for (const [k, v] of Object.entries(doc)) {
    if (k === "format" || k === "version") continue;
    // Underscore-prefixed top-level keys hold YAML anchors only and are not
    // part of the PsmlPacket shape — they exist purely so authors can define
    // `_tcp_options: &tcp_options ...` and reuse via `*tcp_options`.
    if (k.startsWith("_")) continue;
    out[k] = v;
  }
  return out;
}

// Deterministic TS literal emitter — produces compact, stable output so the
// generated file diffs cleanly when YAML changes. We deliberately avoid
// JSON.stringify for the top-level wrapper so the file is a valid TS module
// (typed `Record<string, PsmlPacket>`), but each preset value is emitted as
// JSON (a strict subset of TS object literal syntax for this data shape).
function emit(presets: Record<string, PresetDoc>): string {
  const banner =
    "// AUTO-GENERATED by scripts/build-presets.ts. DO NOT EDIT.\n" +
    "// Edit data/presets/*.psml.yaml and run `npm run build:presets`.\n" +
    "// eslint-disable\n" +
    "/* prettier-ignore */\n";
  const header =
    'import type { PsmlPacket } from "./types";\n\n' +
    "export const PRESETS: Record<string, PsmlPacket> = {\n";
  const body = Object.entries(presets)
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v, null, 2).replace(/\n/g, "\n  ")} as PsmlPacket,`)
    .join("\n");
  const footer = "\n};\n\nexport const PRESET_KEYS: string[] = Object.keys(PRESETS);\n";
  return banner + header + body + footer;
}

function formatAjvErrors(file: string, errors: unknown[]): string {
  const lines = errors.map((e) => {
    const err = e as { instancePath?: string; message?: string; params?: unknown };
    const path = err.instancePath || "(root)";
    return `  ${path}: ${err.message ?? "validation error"} ${JSON.stringify(err.params ?? {})}`;
  });
  return `Schema validation failed for ${relative(REPO_ROOT, file)}:\n${lines.join("\n")}`;
}

function main(): void {
  const schema = loadSchema();
  // ajv-formats publishes both default and named exports; tolerate both via
  // a runtime check so the script works under tsx (ESM) and node (CJS).
  const addFormatsFn = (addFormats as unknown as { default?: typeof addFormats }).default ?? addFormats;
  const AjvCtor = (Ajv2020 as unknown as { default?: typeof Ajv2020 }).default ?? Ajv2020;
  const ajv = new AjvCtor({ allErrors: true, strict: false });
  addFormatsFn(ajv);
  const validate = ajv.compile(schema as object);

  const files = listYamlFiles();
  if (files.length === 0) {
    console.error(`No .psml.yaml files found in ${PRESETS_DIR}`);
    process.exit(1);
  }

  const presets: Record<string, PresetDoc> = {};
  let failed = false;
  for (const file of files) {
    const key = keyFromFilename(file);
    const text = readFileSync(file, "utf8");
    let raw: PresetDoc;
    try {
      raw = parseYaml(text) as PresetDoc;
    } catch (err) {
      console.error(`YAML parse error in ${relative(REPO_ROOT, file)}: ${(err as Error).message}`);
      failed = true;
      continue;
    }
    const stripped = stripValidationFields(raw);
    const forValidation: PresetDoc = { format: FORMAT_TAG, version: FORMAT_VERSION, ...stripped };
    if (!validate(forValidation)) {
      console.error(formatAjvErrors(file, validate.errors ?? []));
      failed = true;
      continue;
    }
    presets[key] = stripped;
  }

  if (failed) {
    process.exit(1);
  }

  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, emit(presets), "utf8");
  console.log(`Wrote ${relative(REPO_ROOT, OUT_PATH)} (${files.length} presets).`);
}

main();
