import { readFileSync, writeFileSync } from "fs";
import { resolve } from "path";

function loadFont(weight: 400 | 700): { base64: string; sizeKB: string } {
  const fontPath = resolve(
    process.cwd(),
    "node_modules",
    "@fontsource",
    "line-seed-jp",
    "files",
    `line-seed-jp-latin-${weight}-normal.woff`,
  );
  const buffer = readFileSync(fontPath);
  return {
    base64: buffer.toString("base64"),
    sizeKB: (buffer.length / 1024).toFixed(1),
  };
}

try {
  const w400 = loadFont(400);
  const w700 = loadFont(700);
  const outputPath = resolve(process.cwd(), "lib", "og-font.ts");

  const toBuffer = (varName: string, b64: string) =>
    `const ${varName}_B64 = "${b64}";\n` +
    `const ${varName}_RAW = Buffer.from(${varName}_B64, "base64");\n` +
    `export const ${varName}: ArrayBuffer = ${varName}_RAW.buffer.slice(${varName}_RAW.byteOffset, ${varName}_RAW.byteOffset + ${varName}_RAW.byteLength);\n`;

  const content =
    `// Auto-generated by scripts/generate-og-font.ts — do not edit\n` +
    toBuffer("OG_FONT_BUFFER", w400.base64) +
    toBuffer("OG_FONT_BUFFER_700", w700.base64);

  writeFileSync(outputPath, content);
  console.log(
    `✓ og-font.ts generated (400: ${w400.sizeKB} KB, 700: ${w700.sizeKB} KB)`,
  );
} catch (error) {
  const message = error instanceof Error ? error.message : String(error);
  console.error(`Failed to generate og-font.ts:`);
  console.error(`  Error: ${message}`);

  if (message.includes("ENOENT")) {
    console.error(`  → Missing dependency. Run: npm ci`);
  } else if (message.includes("EACCES")) {
    console.error(`  → Permission denied. Check file permissions.`);
  } else {
    console.error(`  Ensure @fontsource/line-seed-jp is installed: npm ci`);
  }

  process.exit(1);
}
