import { readFileSync, writeFileSync } from "fs";
import { resolve } from "path";

const fontPath = resolve(
  process.cwd(),
  "node_modules",
  "@fontsource",
  "geist",
  "files",
  "geist-latin-400-normal.woff",
);

try {
  const buffer = readFileSync(fontPath);
  const base64 = buffer.toString("base64");
  const outputPath = resolve(process.cwd(), "lib", "og-font.ts");

  const content = `// Auto-generated by scripts/generate-og-font.ts — do not edit
const GEIST_FONT_B64 = "${base64}";
const fontBuffer = Buffer.from(GEIST_FONT_B64, "base64");
export const OG_FONT_BUFFER: ArrayBuffer = fontBuffer.buffer.slice(fontBuffer.byteOffset, fontBuffer.byteOffset + fontBuffer.byteLength);
`;

  writeFileSync(outputPath, content);
  console.log(
    `✓ og-font.ts generated (${(buffer.length / 1024).toFixed(1)} KB)`,
  );
} catch (error) {
  console.error(
    "Failed to generate og-font.ts:",
    error instanceof Error ? error.message : String(error),
  );
  process.exit(1);
}
