import { readFileSync, writeFileSync } from "fs";
import { resolve } from "path";

const fontPath = resolve(
  process.cwd(),
  "node_modules",
  "@fontsource",
  "line-seed-jp",
  "files",
  "line-seed-jp-japanese-400-normal.woff",
);

try {
  const buffer = readFileSync(fontPath);
  const base64 = buffer.toString("base64");
  const outputPath = resolve(process.cwd(), "lib", "og-font.ts");

  const content = `// Auto-generated by scripts/generate-og-font.ts — do not edit
const LINE_SEED_JP_FONT_B64 = "${base64}";
const fontBuffer = Buffer.from(LINE_SEED_JP_FONT_B64, "base64");
export const OG_FONT_BUFFER: ArrayBuffer = fontBuffer.buffer.slice(fontBuffer.byteOffset, fontBuffer.byteOffset + fontBuffer.byteLength);
`;

  writeFileSync(outputPath, content);
  console.log(
    `✓ og-font.ts generated (${(buffer.length / 1024).toFixed(1)} KB)`,
  );
} catch (error) {
  const message = error instanceof Error ? error.message : String(error);
  console.error(`Failed to generate og-font.ts:`);
  console.error(`  Path attempted: ${fontPath}`);
  console.error(`  Error: ${message}`);

  if (message.includes("ENOENT")) {
    console.error(`  → Missing dependency. Run: npm ci`);
  } else if (message.includes("EACCES")) {
    console.error(`  → Permission denied. Check file permissions.`);
  } else {
    console.error(`  Ensure @fontsource/line-seed-jp is installed: npm ci`);
  }

  process.exit(1);
}
