// AUTO-GENERATED by scripts/migrate-v1-to-v2.ts.
// Manual cleanup is welcome; re-run the script to regenerate.

import type { Packet } from "./types";

const RAW_GENERATED = {
  "dns": {
    "name": "DNS Header",
    "rowBits": 16,
    "byteOrder": "Network byte order (big-endian, MSB-first). All count fields are 16-bit big-endian.",
    "description": "Domain Name System message header (RFC 1035). 12 bytes; the Flags field encodes QR/Opcode/AA/TC/RD/RA/Z/RCODE.",
    "body": [
      {
        "id": "id",
        "name": "Identification",
        "type": {
          "kind": "bits",
          "n": 16
        },
        "category": "identifier",
        "color": "blue",
        "doc": "Random 16-bit ID echoed in the response — lets the resolver match a reply to its outstanding query and helps mitigate spoofing. [RFC 1035, RFC 5452]"
      },
      {
        "kind": "group",
        "id": "flags_bits",
        "name": "Flags",
        "children": [
          {
            "id": "flags_qr",
            "name": "QR",
            "type": {
              "kind": "bits",
              "n": 1
            },
            "category": "flags",
            "color": "rose",
            "doc": "Query/Response — 0 = the message is a query from a client, 1 = the message is a server's response."
          },
          {
            "id": "flags_opcode",
            "name": "Opcode",
            "type": {
              "kind": "bits",
              "n": 4
            },
            "category": "flags",
            "color": "rose",
            "doc": "Kind of operation: 0=QUERY (the normal lookup), 1=IQUERY (obsolete inverse query), 2=STATUS, 4=NOTIFY (zone change), 5=UPDATE (dynamic DNS)."
          },
          {
            "id": "flags_aa",
            "name": "AA",
            "type": {
              "kind": "bits",
              "n": 1
            },
            "category": "flags",
            "color": "rose",
            "doc": "Authoritative Answer — set when the responder is authoritative for the queried zone (e.g. an answer direct from ns1.example.com for example.com)."
          },
          {
            "id": "flags_tc",
            "name": "TC",
            "type": {
              "kind": "bits",
              "n": 1
            },
            "category": "flags",
            "color": "rose",
            "doc": "TrunCation — set when the response was cut off because it didn't fit the transport (typically a 512-byte UDP limit). The client should retry over TCP."
          },
          {
            "id": "flags_rd",
            "name": "RD",
            "type": {
              "kind": "bits",
              "n": 1
            },
            "category": "flags",
            "color": "rose",
            "doc": "Recursion Desired — client asks the server to chase the query through the DNS hierarchy on its behalf rather than just returning a referral."
          },
          {
            "id": "flags_ra",
            "name": "RA",
            "type": {
              "kind": "bits",
              "n": 1
            },
            "category": "flags",
            "color": "rose",
            "doc": "Recursion Available — server advertises whether it supports recursive resolution. Public resolvers like 8.8.8.8 set this; authoritative-only servers do not."
          },
          {
            "id": "flags_z",
            "name": "Z",
            "type": {
              "kind": "bits",
              "n": 3
            },
            "category": "flags",
            "color": "rose",
            "doc": "Reserved bits — must be zero in queries and responses. Two of these were later repurposed by DNSSEC as AD (Authentic Data) and CD (Checking Disabled). [RFC 4035]"
          },
          {
            "id": "flags_rcode",
            "name": "RCODE",
            "type": {
              "kind": "bits",
              "n": 4
            },
            "category": "flags",
            "color": "rose",
            "doc": "Response Code — 0=NOERROR, 1=FORMERR (bad query), 2=SERVFAIL, 3=NXDOMAIN (name does not exist), 4=NOTIMP, 5=REFUSED."
          }
        ]
      },
      {
        "id": "qdcount",
        "name": "QDCOUNT",
        "type": {
          "kind": "bits",
          "n": 16
        },
        "category": "length",
        "color": "teal",
        "doc": "Number of question entries that follow the header — usually 1 (DNS supports more in theory but virtually nobody does in practice)."
      },
      {
        "id": "ancount",
        "name": "ANCOUNT",
        "type": {
          "kind": "bits",
          "n": 16
        },
        "category": "length",
        "color": "green",
        "doc": "Number of resource records in the Answer section — for an A query, the IP addresses returned for the name."
      },
      {
        "id": "nscount",
        "name": "NSCOUNT",
        "type": {
          "kind": "bits",
          "n": 16
        },
        "category": "length",
        "color": "amber",
        "doc": "Number of NS records in the Authority section — points the client at authoritative servers, often used in delegation responses."
      },
      {
        "id": "arcount",
        "name": "ARCOUNT",
        "type": {
          "kind": "bits",
          "n": 16
        },
        "category": "length",
        "color": "orange",
        "doc": "Number of records in the Additional section — typically glue (A/AAAA records for the NS hostnames in the Authority section) or an OPT pseudo-RR for EDNS0."
      }
    ]
  },
  "ipv6": {
    "name": "IPv6 Header",
    "rowBits": 32,
    "byteOrder": "Network byte order (big-endian, MSB-first). Addresses are transmitted high-group first; e.g. 2001:db8::1 is sent as 0x2001 0x0db8 ... 0x0001.",
    "description": "Internet Protocol version 6 header (RFC 8200 §3). Fixed 40 bytes; optional features such as fragmentation and routing live in chained extension headers selected by Next Header.",
    "body": [
      {
        "id": "version",
        "name": "Version",
        "type": {
          "kind": "bits",
          "n": 4
        },
        "category": "type",
        "color": "blue",
        "doc": "IP version field — always 6 for IPv6, distinguishing this header from an IPv4 header that begins with 4. [RFC 8200 §3]"
      },
      {
        "id": "trafficClass",
        "name": "Traffic Class",
        "type": {
          "kind": "bits",
          "n": 8
        },
        "category": "type",
        "color": "orange",
        "doc": "Equivalent of IPv4's DSCP+ECN packed into one byte: top 6 bits are DSCP for QoS classification, bottom 2 bits are ECN for congestion signalling. [RFC 8200, RFC 2474, RFC 3168]"
      },
      {
        "id": "flowLabel",
        "name": "Flow Label",
        "type": {
          "kind": "bits",
          "n": 20
        },
        "category": "identifier",
        "color": "amber",
        "doc": "20-bit label tagging packets that belong to the same flow (e.g. one TCP connection) so routers can keep them on the same path without parsing L4 headers. [RFC 6437]"
      },
      {
        "id": "payloadLength",
        "name": "Payload Length",
        "type": {
          "kind": "bits",
          "n": 16
        },
        "category": "length",
        "color": "teal",
        "doc": "Bytes of payload following this header, including any extension headers. 0 means a Jumbogram (length carried in a Hop-by-Hop option, allowing packets >65535 bytes). [RFC 8200, RFC 2675]"
      },
      {
        "id": "nextHeader",
        "name": "Next Header",
        "type": {
          "kind": "bits",
          "n": 8
        },
        "category": "type",
        "color": "teal",
        "doc": "Type of the immediately following header — uses the same numbering as IPv4 Protocol. e.g. 6=TCP, 17=UDP, 58=ICMPv6, 0=Hop-by-Hop, 43=Routing, 44=Fragment, 50=ESP, 51=AH."
      },
      {
        "kind": "repeat",
        "id": "nextHeader_chain",
        "name": "Next Header (chain)",
        "category": "type",
        "color": "amber",
        "doc": "IPv6 extension-header chain (mechanically migrated).",
        "element": {
          "id": "nextHeader_chainRecord",
          "fields": [
            {
              "kind": "switch",
              "id": "nextHeader_byProto",
              "on": {
                "kind": "ref",
                "field": "nextHeader_proto"
              },
              "cases": {
                "0": {
                  "id": "nextHeader_proto_0",
                  "name": "Hop-by-Hop Options",
                  "fields": [
                    {
                      "id": "nextHeader",
                      "name": "Next Header",
                      "type": {
                        "kind": "bits",
                        "n": 8
                      }
                    },
                    {
                      "id": "hdrExtLen",
                      "name": "Hdr Ext Len",
                      "type": {
                        "kind": "bits",
                        "n": 8
                      }
                    },
                    {
                      "id": "options",
                      "name": "Options + padding",
                      "type": {
                        "kind": "bits",
                        "n": 48
                      }
                    }
                  ]
                },
                "43": {
                  "id": "nextHeader_proto_43",
                  "name": "Routing",
                  "fields": [
                    {
                      "id": "nextHeader",
                      "name": "Next Header",
                      "type": {
                        "kind": "bits",
                        "n": 8
                      }
                    },
                    {
                      "id": "hdrExtLen",
                      "name": "Hdr Ext Len",
                      "type": {
                        "kind": "bits",
                        "n": 8
                      }
                    },
                    {
                      "id": "routingType",
                      "name": "Routing Type",
                      "type": {
                        "kind": "bits",
                        "n": 8
                      }
                    },
                    {
                      "id": "segmentsLeft",
                      "name": "Segments Left",
                      "type": {
                        "kind": "bits",
                        "n": 8
                      }
                    },
                    {
                      "id": "typeSpecific",
                      "name": "Type-Specific Data",
                      "type": {
                        "kind": "bits",
                        "n": 32
                      }
                    }
                  ]
                },
                "44": {
                  "id": "nextHeader_proto_44",
                  "name": "Fragment",
                  "fields": [
                    {
                      "id": "nextHeader",
                      "name": "Next Header",
                      "type": {
                        "kind": "bits",
                        "n": 8
                      }
                    },
                    {
                      "id": "reserved",
                      "name": "Reserved",
                      "type": {
                        "kind": "bits",
                        "n": 8
                      }
                    },
                    {
                      "id": "fragOffset",
                      "name": "Frag Offset",
                      "type": {
                        "kind": "bits",
                        "n": 13
                      }
                    },
                    {
                      "id": "res2",
                      "name": "Res",
                      "type": {
                        "kind": "bits",
                        "n": 2
                      }
                    },
                    {
                      "id": "mFlag",
                      "name": "M",
                      "type": {
                        "kind": "bits",
                        "n": 1
                      }
                    },
                    {
                      "id": "ident",
                      "name": "Identification",
                      "type": {
                        "kind": "bits",
                        "n": 32
                      }
                    }
                  ]
                },
                "50": {
                  "id": "nextHeader_proto_50",
                  "name": "ESP",
                  "fields": [
                    {
                      "id": "spi",
                      "name": "SPI",
                      "type": {
                        "kind": "bits",
                        "n": 32
                      }
                    },
                    {
                      "id": "seq",
                      "name": "Sequence Number",
                      "type": {
                        "kind": "bits",
                        "n": 32
                      }
                    },
                    {
                      "id": "payload",
                      "name": "Encrypted Payload (var)",
                      "type": {
                        "kind": "bits",
                        "n": 64
                      }
                    }
                  ]
                },
                "51": {
                  "id": "nextHeader_proto_51",
                  "name": "AH",
                  "fields": [
                    {
                      "id": "nextHeader",
                      "name": "Next Header",
                      "type": {
                        "kind": "bits",
                        "n": 8
                      }
                    },
                    {
                      "id": "payloadLen",
                      "name": "Payload Len",
                      "type": {
                        "kind": "bits",
                        "n": 8
                      }
                    },
                    {
                      "id": "reserved",
                      "name": "Reserved",
                      "type": {
                        "kind": "bits",
                        "n": 16
                      }
                    },
                    {
                      "id": "spi",
                      "name": "SPI",
                      "type": {
                        "kind": "bits",
                        "n": 32
                      }
                    },
                    {
                      "id": "seq",
                      "name": "Sequence Number",
                      "type": {
                        "kind": "bits",
                        "n": 32
                      }
                    },
                    {
                      "id": "icv",
                      "name": "Integrity Check Value",
                      "type": {
                        "kind": "bits",
                        "n": 96
                      }
                    }
                  ]
                },
                "60": {
                  "id": "nextHeader_proto_60",
                  "name": "Destination Options",
                  "fields": [
                    {
                      "id": "nextHeader",
                      "name": "Next Header",
                      "type": {
                        "kind": "bits",
                        "n": 8
                      }
                    },
                    {
                      "id": "hdrExtLen",
                      "name": "Hdr Ext Len",
                      "type": {
                        "kind": "bits",
                        "n": 8
                      }
                    },
                    {
                      "id": "options",
                      "name": "Options + padding",
                      "type": {
                        "kind": "bits",
                        "n": 48
                      }
                    }
                  ]
                }
              }
            }
          ]
        },
        "count": {
          "kind": "ref",
          "field": "nextHeader_chainCount"
        }
      },
      {
        "id": "hopLimit",
        "name": "Hop Limit",
        "type": {
          "kind": "bits",
          "n": 8
        },
        "category": "identifier",
        "color": "amber",
        "doc": "Hop counter decremented by each forwarding router; the packet is dropped at 0. IPv6 equivalent of IPv4 TTL; default is typically 64. [RFC 8200]"
      },
      {
        "id": "srcAddr",
        "name": "Source Address",
        "type": {
          "kind": "bits",
          "n": 128
        },
        "category": "addressing",
        "color": "blue",
        "doc": "128-bit sender address — written as eight 16-bit hex groups, with :: collapsing one run of zero groups. e.g. 2001:db8::1, fe80::1 (link-local). [RFC 4291]"
      },
      {
        "id": "dstAddr",
        "name": "Destination Address",
        "type": {
          "kind": "bits",
          "n": 128
        },
        "category": "addressing",
        "color": "violet",
        "doc": "128-bit receiver address — also supports multicast (ff00::/8) and anycast. e.g. 2606:4700:4700::1111 is one of Cloudflare's public DNS resolvers. [RFC 4291]"
      }
    ]
  },
  "icmp": {
    "name": "ICMP Echo (IPv4)",
    "rowBits": 32,
    "byteOrder": "Network byte order (big-endian, MSB-first). The Identifier and Sequence Number are 16-bit big-endian.",
    "description": "Internet Control Message Protocol echo request/reply layout (RFC 792). Carried directly inside IPv4 with Protocol=1.",
    "body": [
      {
        "id": "type",
        "name": "Type",
        "type": {
          "kind": "bits",
          "n": 8
        },
        "category": "type",
        "color": "blue",
        "doc": "ICMP message type — selects the kind of control/error message. e.g. 8=Echo Request (ping), 0=Echo Reply, 3=Destination Unreachable, 11=Time Exceeded (used by traceroute). [RFC 792]"
      },
      {
        "id": "code",
        "name": "Code",
        "type": {
          "kind": "bits",
          "n": 8
        },
        "category": "type",
        "color": "violet",
        "doc": "Sub-type within the Type — refines the meaning. e.g. for Type=3 (Destination Unreachable): 0=net unreachable, 1=host unreachable, 3=port unreachable, 4=fragmentation needed and DF set."
      },
      {
        "id": "checksum",
        "name": "Checksum",
        "type": {
          "kind": "bits",
          "n": 16
        },
        "category": "checksum",
        "color": "orange",
        "doc": "16-bit one's-complement checksum over the entire ICMP message (header + data). Detects in-transit corruption. [RFC 1071]"
      },
      {
        "id": "identifier",
        "name": "Identifier",
        "type": {
          "kind": "bits",
          "n": 16
        },
        "category": "identifier",
        "color": "teal",
        "doc": "Echo identifier — lets a sender match replies to its outstanding requests when many are in flight. Often the OS sets this to the ping process's PID."
      },
      {
        "id": "sequence",
        "name": "Sequence Number",
        "type": {
          "kind": "bits",
          "n": 16
        },
        "category": "identifier",
        "color": "amber",
        "doc": "Echo sequence number — incremented for each ping so you can spot dropped replies. e.g. ping shows 'icmp_seq=1, icmp_seq=2, ...'."
      }
    ]
  },
  "icmpv6": {
    "name": "ICMPv6 Echo",
    "rowBits": 32,
    "byteOrder": "Network byte order (big-endian, MSB-first). The Identifier and Sequence Number are 16-bit big-endian.",
    "description": "ICMP for IPv6 echo request/reply layout (RFC 4443). Carried in IPv6 with Next Header=58.",
    "body": [
      {
        "id": "type",
        "name": "Type",
        "type": {
          "kind": "bits",
          "n": 8
        },
        "category": "type",
        "color": "blue",
        "doc": "ICMPv6 message type. e.g. 128=Echo Request, 129=Echo Reply, 1=Destination Unreachable, 3=Time Exceeded, 135/136=NDP Neighbor Solicitation/Advertisement (the IPv6 equivalent of ARP). [RFC 4443]"
      },
      {
        "id": "code",
        "name": "Code",
        "type": {
          "kind": "bits",
          "n": 8
        },
        "category": "type",
        "color": "violet",
        "doc": "Sub-type refining the Type. 0 for Echo Request/Reply; for Type=1 (Destination Unreachable): 0=no route, 3=address unreachable, 4=port unreachable."
      },
      {
        "id": "checksum",
        "name": "Checksum",
        "type": {
          "kind": "bits",
          "n": 16
        },
        "category": "checksum",
        "color": "orange",
        "doc": "16-bit one's-complement checksum over the ICMPv6 message plus an IPv6 pseudo-header (src/dst, length, next header). Mandatory in IPv6. [RFC 4443 §2.3]"
      },
      {
        "id": "identifier",
        "name": "Identifier",
        "type": {
          "kind": "bits",
          "n": 16
        },
        "category": "identifier",
        "color": "teal",
        "doc": "Echo identifier — lets the sender pair replies with outstanding requests; commonly the ping process's PID."
      },
      {
        "id": "sequence",
        "name": "Sequence Number",
        "type": {
          "kind": "bits",
          "n": 16
        },
        "category": "identifier",
        "color": "amber",
        "doc": "Echo sequence number — incremented per ping so dropped responses are visible."
      }
    ]
  },
  "arp": {
    "name": "ARP (IPv4 over Ethernet)",
    "rowBits": 32,
    "byteOrder": "Network byte order (big-endian, MSB-first). HLEN/PLEN are single-byte counts, so endianness only matters for the multi-byte fields.",
    "description": "Address Resolution Protocol packet for IPv4-over-Ethernet (RFC 826). Address fields are technically variable; this preset shows the common HTYPE=1, PTYPE=0x0800, HLEN=6, PLEN=4 form (28 bytes total).",
    "body": [
      {
        "id": "htype",
        "name": "Hardware Type",
        "type": {
          "kind": "bits",
          "n": 16
        },
        "category": "type",
        "color": "blue",
        "doc": "Link-layer technology code — tells the receiver how to interpret the hardware address fields. 1 = Ethernet (the overwhelmingly common case). [RFC 826, IANA ARP parameters]"
      },
      {
        "id": "ptype",
        "name": "Protocol Type",
        "type": {
          "kind": "bits",
          "n": 16
        },
        "category": "type",
        "color": "violet",
        "doc": "Protocol whose address is being resolved — re-uses EtherType numbering. 0x0800 means IPv4 addresses. [RFC 826]"
      },
      {
        "id": "hlen",
        "name": "HLEN",
        "type": {
          "kind": "bits",
          "n": 8
        },
        "category": "length",
        "color": "amber",
        "doc": "Hardware address length in bytes — lets a parser walk past the SHA/THA fields. 6 for Ethernet MAC addresses. [RFC 826]"
      },
      {
        "id": "plen",
        "name": "PLEN",
        "type": {
          "kind": "bits",
          "n": 8
        },
        "category": "length",
        "color": "amber",
        "doc": "Protocol address length in bytes. 4 for IPv4 addresses; 16 would be used if ARP carried IPv6 (in practice IPv6 uses NDP instead). [RFC 826]"
      },
      {
        "id": "oper",
        "name": "Operation",
        "type": {
          "kind": "bits",
          "n": 16
        },
        "category": "type",
        "color": "rose",
        "doc": "What this packet is doing. 1=Request ('who has this IP?'), 2=Reply ('I do, here's my MAC'), 3/4=RARP request/reply (legacy). [RFC 826]"
      },
      {
        "id": "sha",
        "name": "Sender Hardware Address",
        "type": {
          "kind": "bits",
          "n": 48
        },
        "category": "addressing",
        "color": "blue",
        "doc": "Sender's MAC address. Receivers cache the (SPA, SHA) pair so future packets to the sender's IP can be addressed at L2. Length is HLEN bytes; fixed at 48 bits for Ethernet."
      },
      {
        "id": "spa",
        "name": "Sender Protocol Address",
        "type": {
          "kind": "bits",
          "n": 32
        },
        "category": "addressing",
        "color": "teal",
        "doc": "Sender's IPv4 address. Combined with SHA, it tells the LAN 'this IP lives at this MAC'. Gratuitous ARP uses SPA = TPA to announce or detect address conflicts."
      },
      {
        "id": "tha",
        "name": "Target Hardware Address",
        "type": {
          "kind": "bits",
          "n": 48
        },
        "category": "addressing",
        "color": "violet",
        "doc": "Target's MAC address — the value the requester wants to learn. Zero (00:00:00:00:00:00) in an ARP request; filled in on the reply."
      },
      {
        "id": "tpa",
        "name": "Target Protocol Address",
        "type": {
          "kind": "bits",
          "n": 32
        },
        "category": "addressing",
        "color": "teal",
        "doc": "Target's IPv4 address — the address being resolved. e.g. 'who has 192.168.1.1?' carries TPA = 192.168.1.1."
      }
    ]
  },
  "tlsRecord": {
    "name": "TLS Record Layer",
    "rowBits": 8,
    "byteOrder": "Network byte order (big-endian, MSB-first). The 16-bit Length is split here as high byte then low byte.",
    "description": "TLS record layer header (RFC 8446 §5.1). 5-byte fixed header that frames every TLS record on the wire.",
    "body": [
      {
        "id": "type",
        "name": "Content Type",
        "type": {
          "kind": "bits",
          "n": 8
        },
        "category": "type",
        "color": "blue",
        "doc": "What kind of record this carries — drives demultiplexing inside the TLS stack. e.g. 20=ChangeCipherSpec, 21=Alert, 22=Handshake (ClientHello/ServerHello/...), 23=ApplicationData (encrypted HTTP traffic), 24=Heartbeat. [RFC 8446 §5.1]"
      },
      {
        "id": "versionMajor",
        "name": "Version (Major)",
        "type": {
          "kind": "bits",
          "n": 8
        },
        "category": "type",
        "color": "violet",
        "doc": "Legacy record-version major byte — always 0x03 from SSL 3.0 through TLS 1.3. The actual negotiated version lives in the Handshake messages, not here."
      },
      {
        "id": "versionMinor",
        "name": "Version (Minor)",
        "type": {
          "kind": "bits",
          "n": 8
        },
        "category": "type",
        "color": "violet",
        "doc": "Legacy record-version minor byte. 0x01=TLS 1.0, 0x03=TLS 1.2. TLS 1.3 still sends 0x0303 here so middleboxes that hard-code TLS 1.2 don't drop the packet. [RFC 8446 §5.1]"
      },
      {
        "id": "lengthHi",
        "name": "Length (high byte)",
        "type": {
          "kind": "bits",
          "n": 8
        },
        "category": "length",
        "color": "teal",
        "doc": "High byte of the 16-bit big-endian fragment length — receiver uses (Hi << 8) | Lo to know how many bytes follow this header. Max 2^14 + 256 bytes for a TLSCiphertext fragment."
      },
      {
        "id": "lengthLo",
        "name": "Length (low byte)",
        "type": {
          "kind": "bits",
          "n": 8
        },
        "category": "length",
        "color": "teal",
        "doc": "Low byte of the 16-bit big-endian fragment length. Combined with the high byte to give the total bytes of TLS fragment that follow."
      }
    ]
  },
  "tlsClientHello": {
    "name": "TLS ClientHello",
    "rowBits": 32,
    "byteOrder": "Network byte order (big-endian, MSB-first). All length prefixes are big-endian; vectors are length-prefixed per the TLS presentation language (RFC 8446 §3.4).",
    "description": "TLS 1.3 ClientHello handshake message (RFC 8446 §4.1.2). Wraps inside a TLS Record (Content Type=22). Extensions are a TLV list — add SNI, supported_versions, supported_groups, key_share, ALPN as needed.",
    "body": [
      {
        "id": "msgType",
        "name": "Handshake Type",
        "type": {
          "kind": "bits",
          "n": 8
        },
        "category": "type",
        "color": "blue",
        "doc": "Handshake message type — 1 = ClientHello, 2 = ServerHello, etc. [RFC 8446 §4]"
      },
      {
        "id": "length",
        "name": "Handshake Length",
        "type": {
          "kind": "bits",
          "n": 24
        },
        "category": "length",
        "color": "teal",
        "doc": "Length of the handshake message body that follows (legacy_version through extensions). [RFC 8446 §4]"
      },
      {
        "id": "legacyVersion",
        "name": "legacy_version",
        "type": {
          "kind": "bits",
          "n": 16
        },
        "category": "type",
        "color": "violet",
        "doc": "Frozen at 0x0303 (TLS 1.2) for middlebox compatibility — the actual negotiated version is conveyed via the supported_versions extension. [RFC 8446 §4.1.2]"
      },
      {
        "id": "random",
        "name": "random",
        "type": {
          "kind": "bits",
          "n": 256
        },
        "category": "identifier",
        "color": "blue",
        "doc": "32 cryptographically random bytes contributed by the client; mixed into key derivation. [RFC 8446 §4.1.2]"
      },
      {
        "id": "sessionIdLen",
        "name": "session_id length",
        "type": {
          "kind": "bits",
          "n": 8
        },
        "category": "length",
        "color": "teal",
        "doc": "Length of the legacy session_id (0 in pure TLS 1.3, but commonly 32 for middlebox compatibility). [RFC 8446 §4.1.2]"
      },
      {
        "id": "sessionId",
        "name": "session_id",
        "type": {
          "kind": "bits",
          "n": 256
        },
        "category": "identifier",
        "color": "indigo",
        "doc": "Legacy session identifier echoed by the server in its ServerHello — enables middleboxes that expected TLS 1.2 to behave normally. [RFC 8446 §4.1.2]"
      },
      {
        "id": "cipherSuitesLen",
        "name": "cipher_suites length",
        "type": {
          "kind": "bits",
          "n": 16
        },
        "category": "length",
        "color": "teal",
        "doc": "Length in bytes of the cipher_suites vector that follows. [RFC 8446 §4.1.2]"
      },
      {
        "id": "cipherSuites",
        "name": "cipher_suites",
        "type": {
          "kind": "bits",
          "n": 32
        },
        "category": "type",
        "color": "amber",
        "doc": "Ordered list of 16-bit cipher suite identifiers the client supports — e.g. 0x1301 = TLS_AES_128_GCM_SHA256. [RFC 8446 §4.1.2]"
      },
      {
        "id": "compMethodsLen",
        "name": "compression length",
        "type": {
          "kind": "bits",
          "n": 8
        },
        "category": "length",
        "color": "teal",
        "doc": "Length of the legacy compression_methods vector. Must be 1 in TLS 1.3 (compression is forbidden). [RFC 8446 §4.1.2]"
      },
      {
        "id": "compMethods",
        "name": "compression_methods",
        "type": {
          "kind": "bits",
          "n": 8
        },
        "category": "reserved",
        "color": "slate",
        "doc": "Legacy compression methods — must be the single byte 0x00 (null) in TLS 1.3. [RFC 8446 §4.1.2]"
      },
      {
        "id": "extensionsLen",
        "name": "extensions length",
        "type": {
          "kind": "bits",
          "n": 16
        },
        "category": "length",
        "color": "teal",
        "doc": "Total length in bytes of the extensions block that follows.",
        "defaultValue": 0
      },
      {
        "kind": "repeat",
        "id": "extensions",
        "name": "Extensions",
        "category": "variable",
        "color": "amber",
        "doc": "Sequence of TLS extensions (Type, Length, Value). Each extension carries its own internal layout. [RFC 8446 §4.2]",
        "element": {
          "id": "extensions_record",
          "fields": [
            {
              "kind": "switch",
              "id": "extensions_byKind",
              "on": {
                "kind": "ref",
                "field": "extensions_kind"
              },
              "cases": {
                "0": {
                  "id": "extensions_kind_0",
                  "name": "server_name (SNI)",
                  "fields": [
                    {
                      "id": "type",
                      "name": "Type=0",
                      "type": {
                        "kind": "bits",
                        "n": 16
                      }
                    },
                    {
                      "id": "length",
                      "name": "Ext Len",
                      "type": {
                        "kind": "bits",
                        "n": 16
                      }
                    },
                    {
                      "id": "listLen",
                      "name": "List Len",
                      "type": {
                        "kind": "bits",
                        "n": 16
                      }
                    },
                    {
                      "id": "nameType",
                      "name": "Name Type=0",
                      "type": {
                        "kind": "bits",
                        "n": 8
                      }
                    },
                    {
                      "id": "nameLen",
                      "name": "Name Len",
                      "type": {
                        "kind": "bits",
                        "n": 16
                      }
                    },
                    {
                      "id": "hostname",
                      "name": "host_name (var)",
                      "type": {
                        "kind": "bits",
                        "n": 96
                      }
                    }
                  ]
                },
                "10": {
                  "id": "extensions_kind_10",
                  "name": "supported_groups",
                  "fields": [
                    {
                      "id": "type",
                      "name": "Type=10",
                      "type": {
                        "kind": "bits",
                        "n": 16
                      }
                    },
                    {
                      "id": "length",
                      "name": "Ext Len",
                      "type": {
                        "kind": "bits",
                        "n": 16
                      }
                    },
                    {
                      "id": "listLen",
                      "name": "List Len",
                      "type": {
                        "kind": "bits",
                        "n": 16
                      }
                    },
                    {
                      "id": "groups",
                      "name": "named_group_list",
                      "type": {
                        "kind": "bits",
                        "n": 32
                      }
                    }
                  ]
                },
                "16": {
                  "id": "extensions_kind_16",
                  "name": "ALPN",
                  "fields": [
                    {
                      "id": "type",
                      "name": "Type=16",
                      "type": {
                        "kind": "bits",
                        "n": 16
                      }
                    },
                    {
                      "id": "length",
                      "name": "Ext Len",
                      "type": {
                        "kind": "bits",
                        "n": 16
                      }
                    },
                    {
                      "id": "listLen",
                      "name": "Proto List Len",
                      "type": {
                        "kind": "bits",
                        "n": 16
                      }
                    },
                    {
                      "id": "protoLen",
                      "name": "Proto Len",
                      "type": {
                        "kind": "bits",
                        "n": 8
                      }
                    },
                    {
                      "id": "protocol",
                      "name": "protocol (var)",
                      "type": {
                        "kind": "bits",
                        "n": 16
                      }
                    }
                  ]
                },
                "43": {
                  "id": "extensions_kind_43",
                  "name": "supported_versions",
                  "fields": [
                    {
                      "id": "type",
                      "name": "Type=43",
                      "type": {
                        "kind": "bits",
                        "n": 16
                      }
                    },
                    {
                      "id": "length",
                      "name": "Ext Len",
                      "type": {
                        "kind": "bits",
                        "n": 16
                      }
                    },
                    {
                      "id": "vListLen",
                      "name": "Versions Len",
                      "type": {
                        "kind": "bits",
                        "n": 8
                      }
                    },
                    {
                      "id": "versions",
                      "name": "versions",
                      "type": {
                        "kind": "bits",
                        "n": 16
                      }
                    }
                  ]
                },
                "51": {
                  "id": "extensions_kind_51",
                  "name": "key_share",
                  "fields": [
                    {
                      "id": "type",
                      "name": "Type=51",
                      "type": {
                        "kind": "bits",
                        "n": 16
                      }
                    },
                    {
                      "id": "length",
                      "name": "Ext Len",
                      "type": {
                        "kind": "bits",
                        "n": 16
                      }
                    },
                    {
                      "id": "listLen",
                      "name": "Shares Len",
                      "type": {
                        "kind": "bits",
                        "n": 16
                      }
                    },
                    {
                      "id": "group",
                      "name": "group",
                      "type": {
                        "kind": "bits",
                        "n": 16
                      }
                    },
                    {
                      "id": "keyLen",
                      "name": "key Len",
                      "type": {
                        "kind": "bits",
                        "n": 16
                      }
                    },
                    {
                      "id": "key",
                      "name": "key_exchange (var)",
                      "type": {
                        "kind": "bits",
                        "n": 256
                      }
                    }
                  ]
                }
              }
            }
          ]
        },
        "count": {
          "kind": "ref",
          "field": "extensions_count"
        }
      }
    ]
  },
  "quicShort": {
    "name": "QUIC Short Header (1-RTT)",
    "rowBits": 32,
    "byteOrder": "Network byte order (big-endian, MSB-first). The Connection ID and Packet Number bytes are transmitted in the order shown.",
    "description": "QUIC v1 short-header (1-RTT) packet (RFC 9000 §17.3). Connection ID and Packet Number lengths are negotiated out-of-band; this preset assumes an 8-byte Destination CID and 1-byte Packet Number for illustration.",
    "body": [
      {
        "id": "headerForm",
        "name": "Header Form (0=Short)",
        "type": {
          "kind": "bits",
          "n": 1
        },
        "category": "type",
        "color": "blue",
        "doc": "0 = short header (1-RTT, used after the handshake), 1 = long header (Initial/Handshake/0-RTT/Retry, used during connection setup). [RFC 9000 §17.2/17.3]"
      },
      {
        "id": "fixedBit",
        "name": "Fixed Bit",
        "type": {
          "kind": "bits",
          "n": 1
        },
        "category": "reserved",
        "color": "slate",
        "doc": "Must be 1 in QUIC v1 — receivers drop packets where this bit is 0. Helps distinguish QUIC from random UDP traffic and reserved bit patterns. [RFC 9000 §17.2]"
      },
      {
        "id": "spinBit",
        "name": "Spin Bit",
        "type": {
          "kind": "bits",
          "n": 1
        },
        "category": "flags",
        "color": "amber",
        "doc": "Latency spin bit — toggled once per RTT, letting passive on-path observers measure RTT without breaking encryption. Endpoints may disable it for privacy. [RFC 9000 §17.4]"
      },
      {
        "id": "reserved",
        "name": "Reserved",
        "type": {
          "kind": "bits",
          "n": 2
        },
        "category": "reserved",
        "color": "slate",
        "doc": "Reserved bits — protected by header protection on the wire, but must decrypt to 0; otherwise the receiver MUST close the connection with a PROTOCOL_VIOLATION error. [RFC 9000 §17.3.1]"
      },
      {
        "id": "keyPhase",
        "name": "Key Phase",
        "type": {
          "kind": "bits",
          "n": 1
        },
        "category": "flags",
        "color": "rose",
        "doc": "Identifies which set of packet-protection keys is in use; the bit flips when a key update happens, so receivers know to switch to the new keys. [RFC 9000 §6]"
      },
      {
        "id": "pnLen",
        "name": "Packet Number Length",
        "type": {
          "kind": "bits",
          "n": 2
        },
        "category": "length",
        "color": "violet",
        "doc": "Encoded length of the Packet Number field minus 1 — values 0–3 mean 1–4 bytes of packet number. Protected by header protection so on-path observers can't read it. [RFC 9000 §17.3.1]"
      },
      {
        "id": "dcid",
        "name": "Destination Connection ID",
        "type": {
          "kind": "bits",
          "n": 64
        },
        "category": "addressing",
        "color": "teal",
        "doc": "Receiver-chosen Connection ID — lets QUIC survive NAT rebinding and IP address changes (a phone moving from Wi-Fi to LTE). Length is negotiated (0–20 bytes); shown here as 8 bytes."
      },
      {
        "id": "packetNumber",
        "name": "Packet Number",
        "type": {
          "kind": "bits",
          "n": 8
        },
        "category": "identifier",
        "color": "amber",
        "doc": "Truncated packet number — monotonically increasing per packet within an encryption level; used both for AEAD nonce construction and loss detection. 1–4 bytes wide per Packet Number Length. [RFC 9000 §17.1]"
      }
    ]
  },
  "vlan": {
    "name": "Ethernet II + 802.1Q VLAN Tag",
    "rowBits": 32,
    "byteOrder": "Network byte order (big-endian, MSB-first). The TCI (PCP/DEI/VID) is packed into a single 16-bit big-endian field after TPID.",
    "description": "Ethernet II frame header with an inserted 802.1Q VLAN tag (IEEE 802.1Q-2018). 18-byte header: a 4-byte tag (TPID + TCI) sits between Source MAC and the original EtherType.",
    "body": [
      {
        "id": "dstMac",
        "name": "Destination MAC",
        "type": {
          "kind": "bits",
          "n": 48
        },
        "category": "addressing",
        "color": "violet",
        "doc": "48-bit destination MAC — same role as in a plain Ethernet frame. The VLAN tag does not change addressing, only the broadcast domain on the switch."
      },
      {
        "id": "srcMac",
        "name": "Source MAC",
        "type": {
          "kind": "bits",
          "n": 48
        },
        "category": "addressing",
        "color": "blue",
        "doc": "48-bit sender MAC. Switches learn it per-VLAN, so the same MAC can theoretically be reused in different VLANs."
      },
      {
        "id": "tpid",
        "name": "TPID",
        "type": {
          "kind": "bits",
          "n": 16
        },
        "category": "type",
        "color": "orange",
        "doc": "Tag Protocol Identifier — the magic value that announces a VLAN tag is present. 0x8100 for a single 802.1Q tag; 0x88A8 marks an outer 802.1ad (Q-in-Q / provider) tag."
      },
      {
        "id": "pcp",
        "name": "PCP",
        "type": {
          "kind": "bits",
          "n": 3
        },
        "category": "type",
        "color": "rose",
        "doc": "Priority Code Point — 3-bit IEEE 802.1p class-of-service (0–7) that switches use to pick output queues. e.g. 5 for voice, 6 for video, 0 for best-effort."
      },
      {
        "id": "dei",
        "name": "DEI",
        "type": {
          "kind": "bits",
          "n": 1
        },
        "category": "flags",
        "color": "slate",
        "doc": "Drop Eligible Indicator — when set, marks the frame as a candidate to drop first during congestion. Formerly CFI in legacy 802.1Q."
      },
      {
        "id": "vid",
        "name": "VLAN ID",
        "type": {
          "kind": "bits",
          "n": 12
        },
        "category": "identifier",
        "color": "amber",
        "doc": "12-bit VLAN identifier (0–4095) — selects the virtual LAN this frame belongs to. 0=priority-tagged only (no VLAN), 1=default VLAN, 4095=reserved."
      },
      {
        "id": "etherType",
        "name": "EtherType",
        "type": {
          "kind": "bits",
          "n": 16
        },
        "category": "type",
        "color": "teal",
        "doc": "EtherType of the payload after the VLAN tag — the same field that would have appeared in an untagged frame. e.g. 0x0800=IPv4, 0x86DD=IPv6, 0x0806=ARP."
      }
    ]
  }
} as const;

export const GENERATED_PRESETS = RAW_GENERATED as unknown as Record<string, Packet>;
