// Worksheet template (Typst).
//
// Compiled in-browser by lib/worksheet-typst.ts. The packet description and
// resolved field list are injected via sys.inputs["packet"] (a JSON-encoded
// blob). The `answers` flag toggles answer-key vs student-copy rendering.
//
// Keep this file small and self-contained; the typst.ts WASM environment is
// strict about external assets.

#let packet-json = sys.inputs.at("packet", default: "{}")
#let packet = json(bytes(packet-json))
#let answers = sys.inputs.at("answers", default: "false") == "true"

#set page(
  paper: "us-letter",
  margin: (top: 1.6cm, bottom: 1.6cm, left: 1.4cm, right: 1.4cm),
  numbering: "1",
)
#set text(font: ("Liberation Sans", "DejaVu Sans"), size: 10pt)
#set par(leading: 0.55em)

#let blank = "______"
#let mode-badge = if answers [
  #box(fill: rgb("#111"), inset: (x: 6pt, y: 2pt), radius: 3pt)[
    #text(fill: white, weight: "bold", size: 8pt)[ANSWER KEY]
  ]
] else [
  #box(stroke: 0.6pt + rgb("#333"), inset: (x: 6pt, y: 2pt), radius: 3pt)[
    #text(weight: "bold", size: 8pt)[WORKSHEET]
  ]
]

// ----- Header bar -----
#grid(
  columns: (1fr, auto),
  align: (left + bottom, right + bottom),
  gutter: 1em,
  [
    #text(size: 16pt, weight: "bold")[#packet.name] #h(8pt) #mode-badge \
    #text(size: 9pt, fill: rgb("#555"))[Packet View — printable worksheet]
  ],
  [
    #text(size: 10pt)[
      Name: #box(width: 4.5cm, stroke: (bottom: 0.6pt + rgb("#333")))[#h(1fr)] #h(1em)
      Date: #box(width: 2.5cm, stroke: (bottom: 0.6pt + rgb("#333")))[#h(1fr)]
    ]
  ],
)
#v(0.4em)
#line(length: 100%, stroke: 0.8pt + rgb("#222"))
#v(0.5em)

#if packet.at("description", default: "") != "" [
  #text(size: 9pt, fill: rgb("#444"))[#packet.description]
  #v(0.4em)
]

// ----- Visual diagram (simple sequential field strip) -----
//
// Print a flow of named (or blanked) boxes with each field's bit width below,
// rather than an exact bit-aligned grid; this keeps the template robust to any
// packet layout the resolver produces.
#text(size: 10pt, weight: "bold")[Diagram]
#v(0.3em)
#let label-for(f) = if answers { f.name } else { blank }
#block(
  inset: 6pt,
  stroke: 0.6pt + rgb("#555"),
  radius: 4pt,
  width: 100%,
)[
  #grid(
    columns: (1fr,) * 4,
    gutter: 4pt,
    ..packet.fields.map(f => box(
      width: 100%,
      stroke: 0.5pt + rgb("#888"),
      inset: 4pt,
      radius: 3pt,
    )[
      #align(center)[
        #text(size: 9pt, weight: "bold")[#label-for(f)] \
        #text(size: 8pt, font: "DejaVu Sans Mono", fill: rgb("#555"))[
          #f.bits b / #(calc.quo(f.bits, 8))B
        ] \
        #text(size: 7pt, fill: rgb("#777"))[offset #f.offset]
      ]
    ]),
  )
]

#v(0.6em)

// ----- Fill-in table -----
#text(size: 10pt, weight: "bold")[Fields]
#v(0.3em)

#table(
  columns: (auto, auto, 1fr),
  stroke: 0.4pt + rgb("#555"),
  inset: 5pt,
  align: (center + horizon, left + horizon, left + horizon),
  table.header(
    [#text(weight: "bold", size: 9pt)[#]],
    [#text(weight: "bold", size: 9pt)[Size & offset]],
    [#text(weight: "bold", size: 9pt)[#if answers { "Field name (answer)" } else { "Field name" }]],
  ),
  ..packet.fields.enumerate().map(((i, f)) => (
    [#text(size: 9pt)[#(i + 1)]],
    [#text(size: 9pt, font: "DejaVu Sans Mono")[
      #f.bits bits @ bit #f.offset
    ]],
    if answers [
      #text(size: 10pt)[#f.name]
    ] else [
      // Tall empty cell with a faint bottom rule.
      #box(width: 100%, height: 1.2em)[#h(1fr)]
    ],
  )).flatten(),
)

#v(0.6em)
#line(length: 100%, stroke: 0.3pt + rgb("#ddd"))
#text(size: 8pt, fill: rgb("#777"))[
  Generated by Packet View — #if answers { "Answer key" } else { "Student copy" }
]
