// Client-safe preset access — lightweight index + lazy per-preset fetch.
//
// The 184 built-in presets (~960 KB) no longer ship in the client bundle. This
// module exposes only:
//   * `PRESET_INDEX` / `PRESET_KEYS` — a tiny `{ key: { name } }` map (bundled,
//     generated by `scripts/build-presets.ts`) for the preset picker.
//   * `loadPreset(key)` — fetches one adapted Packet from `/presets/<key>.json`
//     on demand (memoised), used when the user actually selects a preset.
//   * `loadedPresets()` — the presets fetched so far this session, for callers
//     that compare against built-ins without forcing every preset to load.
//
// Server routes that need the whole set import `presets.server.ts` instead
// (which never reaches the client bundle).

import type { Packet } from "./types";
import { PRESET_INDEX } from "./preset-index.generated";

export { PRESET_INDEX, PRESET_KEYS } from "./preset-index.generated";

const cache = new Map<string, Packet>();
// In-flight fetches, memoised so concurrent callers for the same key (e.g. the
// PacketViewer `packetKey` effect and a switch handler firing together) share
// one request instead of racing two.
const inFlight = new Map<string, Promise<Packet>>();

/**
 * Fetch a single built-in preset's full Packet from its static JSON asset.
 * Results are memoised for the session so re-selecting a preset is free, and
 * concurrent loads of the same key share a single in-flight request. The served
 * JSON is already `rowBits`-adapted at build time (see
 * `scripts/build-presets.ts`), so callers get the same shape the server's
 * `presets.server.ts` produces.
 */
export function loadPreset(key: string): Promise<Packet> {
  const cached = cache.get(key);
  if (cached) return Promise.resolve(cached);
  const pending = inFlight.get(key);
  if (pending) return pending;
  const request = (async () => {
    const res = await fetch(`/presets/${encodeURIComponent(key)}.json`);
    if (!res.ok) {
      throw new Error(`Failed to load preset "${key}" (HTTP ${res.status}).`);
    }
    const packet = (await res.json()) as Packet;
    cache.set(key, packet);
    return packet;
  })();
  inFlight.set(key, request);
  // Clear the in-flight slot once settled so a failed fetch can be retried.
  void request.finally(() => inFlight.delete(key));
  return request;
}

/**
 * Seed the session cache with a preset body the client already has (e.g. the
 * initial preset the server resolved and passed as a prop), so `getLoadedPreset`
 * returns it on the very first render without a fetch. Idempotent; never
 * overwrites an existing entry.
 */
export function primePreset(key: string, packet: Packet): void {
  if (!cache.has(key)) cache.set(key, packet);
}

/**
 * Synchronously read an already-fetched built-in preset from the session cache,
 * or `undefined` if it hasn't been `loadPreset`ed yet. Callers that switch to a
 * preset await `loadPreset` first, so by the time the active key points at it
 * the body is cached and this returns it.
 */
export function getLoadedPreset(key: string): Packet | undefined {
  return cache.get(key);
}

/**
 * The built-in presets fetched so far this session, as `[key, packet]` entries.
 * Lazy by nature: a preset only appears here once `loadPreset` has resolved it.
 * Used where comparing against *loaded* built-ins is enough (e.g. the studio's
 * "did my edit return to a built-in preset?" canonicalisation) without forcing
 * all 184 bodies into the client.
 */
export function loadedPresets(): Array<[string, Packet]> {
  return [...cache.entries()];
}

/** Synchronous lookup of a preset's display name from the bundled index. */
export function presetName(key: string): string | undefined {
  return PRESET_INDEX[key]?.name;
}
